apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: trainbot
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: ./helm/trainbot
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
      interval: 1m
  values:
    image:
      tag: "be4fa105a0ac282be11fcc41cfd686a67fcb031a" # This will be updated by CI/CD
      pullPolicy: Always
    env:
      SECRET_NAME: "trainbot-slack-secrets"
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 200m
        memory: 256Mi
  valuesFrom:
    - kind: ConfigMap
      name: flux-vars
      valuesKey: GCP_PROJECT_ID
      targetPath: image.projectId
    - kind: ConfigMap
      name: flux-vars
      valuesKey: GCP_PROJECT_ID
      targetPath: env.GCP_PROJECT_ID
