apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: trainbot
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: ./helm/trainbot
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
      interval: 1m
  values:
    image:
      repository: europe-west2-docker.pkg.dev/${GCP_PROJECT_ID}/trainbot-repo/trainbot
      tag: "be4fa105a0ac282be11fcc41cfd686a67fcb031a" # This will be updated by CI/CD
      pullPolicy: Always
    env:
      GCP_PROJECT_ID: "${GCP_PROJECT_ID}"
      SECRET_NAME: "trainbot-slack-secrets"
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 200m
        memory: 256Mi
