apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: trainbot
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: ./helm/trainbot
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
      interval: 1m
  values:
    image:
      repository: europe-west2-docker.pkg.dev/${gcp_project_id}/trainbot-repo/trainbot
      tag: "latest" # This will be updated by CI/CD
      pullPolicy: Always
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 200m
        memory: 256Mi
